# Generated by Django 5.0.7 on 2024-08-31 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='nome_alunp',
            new_name='nome_aluno',
        ),
    ]
